# Server Configuration
server.port=8081

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/crashcourse
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/crashcourse/protocol/openid-connect/certs